sudo: required
dist: trusty

language: node_js
node_js:
    - '12'

cache:
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn test

after_success:
    - test $TRAVIS_BRANCH = "master" && yarn publisher
