language: node_js
sudo: false
node_js:
    - '12.0.0'

cache:
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn test

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && chmod +x publish.sh && sh publish.sh
